### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by guru9710** [aashishrai3799/Automated-Attendance-System-using-CNN#1]
Can you please upload all the dataset along with the images and the mp4 video? And can you please elaborate the steps in README file?

**Comment by aashishrai3799** [comment]
I regret, but due to the security reasons, I can not upload the dataset and class CCTV footage. However, I'll update the readme file  mentioning all the steps to run the software ASAP. I'll also mention the steps to generate your own customised dataset.
