### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by StasBurenin** [aashishrai3799/Automated-Attendance-System-using-CNN#3]
Hello
how to solve a problem?
ValueError: could not broadcast input array from shape (194,152,3) into shape (160,160,3)
![image](https://user-images.githubusercontent.com/22364087/111145048-e3e6a980-8598-11eb-874e-99441848e1a8.png)

**Comment by aashishrai3799** [comment]
Hi, 

I am assuming you are getting this error while training.
In such a case, you need to resize your training data to (160x160x3) before starting the training. To do so, you may use the "Image.resize()" function from the "PIL" library.

https://pillow.readthedocs.io/en/stable/_modules/PIL/Image.html#Image.resize
https://www.geeksforgeeks.org/python-pil-image-resize-method/

**Comment by StasBurenin** [comment]
Thanks!
